//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Absence
    {
        public int id_absence { get; set; }
        public System.DateTime date { get; set; }
        public bool is_justified { get; set; }
        public bool can_be_justified { get; set; }
        public int fk_student { get; set; }
        public int fk_teacher_subject { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Teacher_Subject Teacher_Subject { get; set; }
    }
}
