//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        public Assignment()
        {
            this.Materials = new HashSet<Material>();
        }
    
        public int id_assignment { get; set; }
        public bool has_midterm { get; set; }
        public int fk_class { get; set; }
        public int fk_teacher_subject { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Teacher_Subject Teacher_Subject { get; set; }
        public virtual ICollection<Material> Materials { get; set; }
    }
}
