//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public Class()
        {
            this.Class_Subject = new HashSet<Class_Subject>();
            this.Student = new HashSet<Student>();
        }
    
        public short id_class { get; set; }
        public string name { get; set; }
        public byte year { get; set; }
        public string field { get; set; }
    
        public virtual ICollection<Class_Subject> Class_Subject { get; set; }
        public virtual ICollection<Student> Student { get; set; }
    }
}
