//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class_Teacher
    {
        public short id_classteacher { get; set; }
        public int fk_teacher { get; set; }
        public int fk_class_subject { get; set; }
    
        public virtual Class_Master Class_Master { get; set; }
        public virtual Class_Subject Class_Subject { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
