//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class_Subject
    {
        public Class_Subject()
        {
            this.Class_Teacher = new HashSet<Class_Teacher>();
            this.Material = new HashSet<Material>();
            this.Situation = new HashSet<Situation>();
        }
    
        public int id_class_subject { get; set; }
        public Nullable<bool> has_midterm { get; set; }
        public short fk_class { get; set; }
        public byte fk_subject { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual ICollection<Class_Teacher> Class_Teacher { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual ICollection<Material> Material { get; set; }
        public virtual ICollection<Situation> Situation { get; set; }
    }
}
