//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class SchoolEntities : DbContext
    {
        public SchoolEntities()
            : base("name=SchoolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Absence> Absence { get; set; }
        public DbSet<Admin> Admin { get; set; }
        public DbSet<Class> Class { get; set; }
        public DbSet<Class_Master> Class_Master { get; set; }
        public DbSet<Class_Subject> Class_Subject { get; set; }
        public DbSet<Class_Teacher> Class_Teacher { get; set; }
        public DbSet<Grade> Grade { get; set; }
        public DbSet<Material> Material { get; set; }
        public DbSet<Person> Person { get; set; }
        public DbSet<Situation> Situation { get; set; }
        public DbSet<Student> Student { get; set; }
        public DbSet<Subject> Subject { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Teacher> Teacher { get; set; }
        public DbSet<Term> Term { get; set; }
    
        public virtual ObjectResult<selectPersone_Result> selectPersone()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selectPersone_Result>("selectPersone");
        }
    }
}
