//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Situation
    {
        public Situation()
        {
            this.Grade = new HashSet<Grade>();
        }
    
        public int id_situation { get; set; }
        public bool debtor { get; set; }
        public bool complete_situation { get; set; }
        public int fk_student { get; set; }
        public int fk_subject { get; set; }
    
        public virtual Class_Subject Class_Subject { get; set; }
        public virtual ICollection<Grade> Grade { get; set; }
        public virtual Student Student { get; set; }
    }
}
