//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Situation_Subject
    {
        public Situation_Subject()
        {
            this.Grades = new HashSet<Grade>();
        }
    
        public int id_situation { get; set; }
        public bool is_debtor { get; set; }
        public bool is_situation_complete { get; set; }
        public int final_grade { get; set; }
        public int fk_student { get; set; }
        public int fk_teacher_subject { get; set; }
    
        public virtual ICollection<Grade> Grades { get; set; }
        public virtual Student Student { get; set; }
        public virtual Teacher_Subject Teacher_Subject { get; set; }
    }
}
