//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Absence = new HashSet<Absence>();
            this.Situation = new HashSet<Situation>();
        }
    
        public int fk_student { get; set; }
        public short fk_class { get; set; }
    
        public virtual ICollection<Absence> Absence { get; set; }
        public virtual Class Class { get; set; }
        public virtual Person Person { get; set; }
        public virtual ICollection<Situation> Situation { get; set; }
    }
}
