//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public Subject()
        {
            this.Teacher_Subject = new HashSet<Teacher_Subject>();
        }
    
        public int id_subject { get; set; }
        public string name { get; set; }
        public int term { get; set; }
    
        public virtual ICollection<Teacher_Subject> Teacher_Subject { get; set; }
    }
}
