//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public Teacher()
        {
            this.Class_Teacher = new HashSet<Class_Teacher>();
            this.Material = new HashSet<Material>();
        }
    
        public int id_teacher { get; set; }
    
        public virtual ICollection<Class_Teacher> Class_Teacher { get; set; }
        public virtual ICollection<Material> Material { get; set; }
        public virtual Person Person { get; set; }
    }
}
