//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher_Subject
    {
        public Teacher_Subject()
        {
            this.Absences = new HashSet<Absence>();
            this.Assignments = new HashSet<Assignment>();
            this.Situation_Subject = new HashSet<Situation_Subject>();
        }
    
        public int id_teacher_subject { get; set; }
        public int fk_teacher { get; set; }
        public int fk_subject { get; set; }
    
        public virtual ICollection<Absence> Absences { get; set; }
        public virtual ICollection<Assignment> Assignments { get; set; }
        public virtual ICollection<Situation_Subject> Situation_Subject { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
